apiVersion: v1
kind: Pod
metadata:
  name: nginx-webhook
  labels:
    app: nginx
  namespace: kod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kod
spec:
  selector:
    app: nginx
  ports:
  - name: http-nginx
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
